#!/bin/bash
#Linux (.deb based distros: Debian, Ubuntu)
#You'll need these base packages to build/package/test/use Harbour:
#sudo apt-get install bash git gcc binutils fakeroot debhelper valgrind upx uncrustify
#sudo apt-get install libncurses-dev
#sudo apt-get install libslang2-dev OR
#sudo apt-get install libslang1-dev
#sudo apt-get install libx11-dev
#sudo apt-get install libgpm-dev OR
#sudo apt-get install libgpmg1-dev
#sudo apt-get install liballegro4.2-dev
#sudo apt-get install libcairo2-dev
#sudo apt-get install libcups2-dev
#sudo apt-get install libcurl4-openssl-dev OR
#sudo apt-get install libcurl4-gnutls-dev
#sudo apt-get install firebird2.1-dev OR
#sudo apt-get install libfirebird2.0-dev
#sudo apt-get install libfreeimage-dev
#sudo apt-get install libgd2-xpm-dev OR
#sudo apt-get install libgd-xpm-dev
#sudo apt-get install libgs-dev
#sudo apt-get install libmagic-dev
#sudo apt-get install libmysqlclient15-dev
#sudo apt-get install unixodbc-dev
#sudo apt-get install libpq-dev
#sudo apt-get install libqt5-dev
#sudo apt-get install libbz2-dev
#sudo apt-get install zlib1g-dev
#sudo apt-get install libpcre3-dev
#sudo apt-get install libsqlite3-dev
#sudo apt-get install libexpat1-dev

#ARCH
#pacman -S freeimage ghostscript libfbclient libxslt unixodbc libmariadbclient gd rabbitmq libfbclient postgresql libcups

#export HB_COMPILER=clang
#export HB_COMPILER=gcc
export HB_INSTALL_PREFIX=/usr
export HB_BUILD_VERBOSE=yes
export HB_WITH_X11=no
export HB_BUILD_STRIP=bin
export HB_BUILD_ADDONS=yes
export HB_BUILD_MODE=cpp 	# Change default build mode to C++ or C. Default: c, except for msvc* compilers, where it's cpp.
#export HB_BUILD_MODE=c
export HB_INSTALL_IMPLIB=yes
export HB_BUILD_CONTRIB_DYN=yes
#export HB_BUILD_CONTRIBS="hbcups hbhpdf hbct hbfship hbmemio hbmisc hbmzip hbnetio hbnf hbtip hbwin hbxpp hbzebra rddbm xhb hbblink hbct hbxpp xhb hboslib hbgt hbgzio"
export HB_BUILD_CONTRIBS=
export HB_BUILD_SHARED=yes
export HB_INSTALL_DOC=yes

echo $HB_BUILD_MODE
echo $HB_BUILD_CONTRIBS
echo $HB_BUILD_ADDONS

# How to Create Packages for Distribution
# Source .tgz on *nix
	# package/mpkg_src.sh

#Binary .tgz on *nix
	#export HB_BUILD_PKG=yes
	#make clean install

#Binary .deb on Linux
	#fakeroot debian/rules binary

#Binary .rpm on Linux
	#package/mpkg_rpm.sh


#HB_WITH_CURSES= (on \*nix systems and DJGPP, auto-detected on both)
#HB_WITH_GPM= (on Linux only)
##HB_WITH_PCRE2=C:\pcre2 (defaults to locally hosted copy if not found)
#HB_WITH_PCRE=C:\pcre (defaults to locally hosted copy if not found)
#HB_WITH_PNG=C:\libpng (defaults to locally hosted copy if not found)
#HB_WITH_SLANG= (on \*nix systems)
#HB_WITH_WATT= (on MS-DOS systems)
#HB_WITH_X11= (on \*nix systems)
#HB_WITH_ZLIB=C:\zlib (defaults to locally hosted copy if not found)

make
sudo make install
#make install DESTDIR=/home/vcatafesta/build/harbour-3.4
